---
- name: "Create Fluent Agent directory"
  ansible.builtin.file:
    dest: "/etc/td-agent-bit"
    state: directory
    mode: 0644 
- name: Curl install
  ansible.builtin.shell: "curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh"
