---
# tasks file for ansible-role-fluentbit

- name: Install Fluentbit
  include_tasks: 'install-{{ ansible_os_family }}.yml'
  tags: ['install']

- name: Install fluentbit package
  package:
    name: td-agent-bit
    state: present
    update_cache: true
  notify: Restart Fluentbit service
  tags: ['install']
  when: "'Container-Optimized' not in ansible_os_family"

- import_tasks: configure.yml
  tags: ['configure']
